tmux:
    symbols:
        branch: '⎇ '
        hashprefix: ':'
        ahead: ↑·
        behind: ↓·
        staged: '● '
        conflict: '✖ '
        modified: '✚ '
        untracked: '… '
        stashed: '⚑ '
        clean: ✔
        insertions: Σ
        deletions: Δ
    styles:
        clear: '#[fg=orange,bg=default]'
        state: '#[fg=green,bg=default]'
        branch: '#[fg=white,bold,bg=default]'
        remote: '#[fg=cyan,bg=default]'
        divergence: '#[fg=magenta]'
        staged: '#[fg=green,bg=black]'
        conflict: '#[fg=yellow,bold,bg=red]'
        modified: '#[fg=yellow,bold,bg=default]'
        untracked: '#[fg=red,bold]'
        stashed: '#[fg=cyan,bold]'
        clean: '#[fg=green,bold,bg=black]'
        insertions: '#[fg=yellow,bright,bg=black]'
        deletions: '#[fg=red,bright,bg=black]'
    #layout: [branch, .., remote-branch, divergence, '- ', flags]
    layout: [branch, " ¦ ", remote-branch, divergence, " ¦ ", flags, " «", stats, "»"]
    options:
        branch_max_len: 12
        branch_trim: left
        ellipsis: …
        hide_clean: false
        swap_divergence: true
        divergence_space: true

