set -g default-shell /bin/zsh

set-window-option -g automatic-rename on

set-option -g set-titles on
set-option -g default-terminal screen-256color
set-option -ag message-style fg=yellow,blink; set-option -ag message-style bg=black

# osx "brew install .."
#set-option -g default-command "reattach-to-user-namespace -l zsh"

setw -g mode-keys vi

setw -g mouse on

set -g history-limit 10000
set -g escape-time 1

setw -g monitor-activity on
set -g visual-activity on

set-window-option -g window-status-fg brightmagenta
set-window-option -g window-status-bg colour236
set-window-option -g window-status-attr dim

set-window-option -g window-status-current-fg brightwhite
set-window-option -g window-status-current-bg colour236
set-window-option -g window-status-current-attr bright

set-option -g status-bg colour235
set-option -g status-fg yellow
set-option -g status-attr dim

set -g status-interval 2
set -g display-time 1000
set -g status-left-length 400
set -g status-left '#(whoami)@#h :: '
set -g status-justify centre
set -g status-right-length 200
set -g status-right '#[bg=default,brightdefault]#(gitmux -cfg $HOME/.gitmux.conf "#{pane_current_path}") #[fg=greenbg=default,dim]#(tmux-mem-cpu-load) :: #[fg=yellow,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") «» #[fg=cyan,bg=default]%H:%M:%S %a›%d/%m/%y'

set-option -ga terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@'

