#!/usr/bin/env bash
#
# Bootstraps user environment and software toolchain
#

source bootstrap.conf

function is_excluded?() {
  for f in ${d_excl_files}; do
    [[ ${f} == *${files}* ]] && return 1
  done
  return
}

function is_os?() {
  case $(uname) in
  *Linux*)  printf "linux"   ;;
  *Darwin*) printf "macosx"  ;;
  *SunOS*)  printf "solaris" ;;
  *BSD*)    printf "bsd"     ;;
  esac
  return
}

function is_distro?() {
  case $(< /etc/*release*) in
  *Debian* | *Ubuntu*)
    printf "debian"
  ;;
  *"Red Hat"* | *CentOS*)
    printf "rh"
  ;;
  esac
  return
}

function install_pkgs() {
  case $(uname) in
  *Linux*)
    $(which apt-get &>/dev/null) || {
      echo "not debian based, do this manually."
      exit 1
    }
    sudo apt-get install -y ${d_pkg_debian}
  ;;
  *Darwin*)
    echo "Homebrew will be set-up - package lists to be added"
    exit 1
  ;;
  esac
}

git submodule update
git submodule foreach git pull

# OS/Distro relevant changes

## OS X Usability changes, Terminal settings etc.
## [ note: quite a lot of this has been copied from elsewhere, from people that maintain & ]
## [ regularly update preferences and checks relevant to change OS X system configs, plist ]
## [ entries and settings. In this case particularly from kdeldycke/dotfiles - thanks!     ]
[[ $(is_os?) == "macosx" ]] && {
  # First close system prefs so nothing can overwrite the following changes
  osascript -e 'tell application "System Preferences" to quit'

  # verbose boot (kernel bootup instead of loading Apple screen)
  printf "> attempting to set verbose boot\n\n" && sudo nvram boot-args="-v"
  
  # make zsh universal default
  printf "> make zsh universal default shell\n\n"
  sudo chsh -s /bin/zsh $USERNAME
  sudo chsh -s /bin/zsh root
  
  # set developer mode
  printf "> setting dev mode\n\n"
  sudo spctl developer-mode enable-terminal
  
  printf "> setting terminal specific options:\n\n"
  # Only use UTF-8 in Terminal.app
  printf "| - utf8 only  "
  defaults write com.apple.terminal StringEncodings -array "4" && printf "[x]\n"
  
  # Enable “focus follows mouse” for Terminal.app and all X11 apps
  # i.e. hover over a window and start typing in it without clicking first
  printf "| - follow mouse focus with multiple open windows  "
  defaults write com.apple.terminal FocusFollowsMouse -bool true &&
  defaults write org.x.X11 wm_ffm -bool true 			 &&
  defaults write org.x.X11 wm_click_through -bool true		 && printf "[x]\n"

  # Enable Secure Keyboard Entry in Terminal.app
  # See: https://security.stackexchange.com/a/47786/8918
  printf "| - secure keyboard entry  "
  defaults write com.apple.terminal SecureKeyboardEntry -bool true && printf "[x]\n"

  printf "| - finally set misc terminal.app config settings..\n"
  # Disable the annoying line marks
  defaults write com.apple.Terminal ShowLineMarks -int 0
 
  printf "| - ..and copy com.apple.Terminal.plist to ~/Library/Preferences/\n" 
  # Copy my personal terminal plist settings to my user preferences
  cp dist/osx/plists/com.apple.Terminal.plist ~/Library/Preferences/
  printf "! \033[1mDONE\033[0m [setting up terminal and OS specific settings]\n\n"


  # Finally set-up Homebrew for software packages
  printf "> setting up Homebrew for package install:\n\n"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" || exit 1  
}

# Set-up specified software packages for running OS/Distro
install_pkgs


#XXX/TODO(azet): add python pips / ruby gems
#XXX/TODO(azet): link all the things

#EOF
