#!/usr/bin/env bash
#
# Bootstraps user environment and software toolchain
#
set -oe pipefail

## lib functions
source lib/os.inc
source lib/bar.inc

## config
source bootstrap.conf


# ----------------------
# main bootstrap process
# ----------------------

# bootstrap submodules
echo "${CLI}> initializing, updating and pulling git submodules:${RST}"
{ 
  git submodule sync --recursive
  git submodule update --init --recursive --jobs 8 --depth 2 -f
  git submodule foreach 'echo $sm_path `git rev-parse HEAD && git status`'
} && printf "\n\n${CLI}> git submodules updated!${RST}\n" \
  || ( printf "${ERR}! error updating git submodules.. !! BUT CONTINUING !! ${RST} \n\n" )


printf "${CLI}> will need super-user privileges (sudo) soon.. so I need your ${RST}"
{
  sudo printf "${CLI}> -- got sudo privs. --\n${RST}"
} || ( printf "${EXI}[-]\n! error obtaining sudo privs. !! EXITING !! ${RST}\n\n" && exit 1 )



# zsh relevant default conf: grml
printf "${CLI}> adding /etc/zshrc from grml zsh:  "
{
    sudo curl --output /etc/zshrc https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc -s
} && printf "[x]\n${RST}" \
  || ( printf "${EXI}[-]\n! error downloading and setting zshrc in /etc !! EXITING !! \n\n${RST}" && exit 1 )

# vim janus config
printf "${CLI}> adding and bootstrapping vim janus config: "
{
  curl -s -L https://bit.ly/janus-bootstrap | bash &>/dev/null 
} && printf "[x]\n${RST}" \
  || ( printf "${ERR}! error bootstrapping vim janus.. !! BUT CONTINUING !! ${RST} \n\n" )

# OS/Distro relevant changes

## OS X Usability changes, Terminal settings etc.
## [ note: quite a lot of this has been copied from elsewhere, from people that maintain & ]
## [ regularly update preferences and checks relevant to change OS X system configs, plist ]
## [ entries and settings. In this case particularly from kdeldycke/dotfiles - thanks!     ]
[[ $(is_os?) == "macosx" ]] && {
  # First close system prefs so nothing can overwrite the following changes
  osascript -e 'tell application "System Preferences" to quit'

  # verbose boot (kernel bootup instead of loading Apple screen)
  printf "${CLI}> attempting to set verbose boot\n${RST}" && sudo nvram boot-args="-v"
  
  # make zsh universal default
  printf "${CLI}> make zsh universal default shell\n${RST}"
  sudo chsh -s /bin/zsh $USERNAME
  sudo chsh -s /bin/zsh root
  
  # set developer mode
  printf "${CLI}> setting dev mode\n\n${RST}"
  sudo spctl developer-mode enable-terminal

  printf "${CLI}> installing xcode cli tools\n\n${RST}"
  xcode-select --install || continue

  printf "${CLI}> setting terminal specific options:\n\n"
  # Only use UTF-8 in Terminal.app
  printf "| - utf8 only  "
  defaults write com.apple.terminal StringEncodings -array "4" && printf "[x]\n"
  
  # Enable “focus follows mouse” for Terminal.app and all X11 apps
  # i.e. hover over a window and start typing in it without clicking first
  printf "| - follow mouse focus with multiple open windows  "
  defaults write com.apple.terminal FocusFollowsMouse -bool true &&
  defaults write org.x.X11 wm_ffm -bool true 			 &&
  defaults write org.x.X11 wm_click_through -bool true		 && printf "[x]\n"

  # Enable Secure Keyboard Entry in Terminal.app
  # See: https://security.stackexchange.com/a/47786/8918
  printf "| - secure keyboard entry  "
  defaults write com.apple.terminal SecureKeyboardEntry -bool true && printf "[x]\n"

  printf "| - finally set misc terminal.app config settings..\n"
  # Disable the annoying line marks
  defaults write com.apple.Terminal ShowLineMarks -int 0

  printf "| - ..and copy com.apple.Terminal.plist to ~/Library/Preferences/\n" 
  # Copy my personal terminal plist settings to my user preferences
  cp dist/osx/plists/com.apple.Terminal.plist ~/Library/Preferences/
  printf "| - !!DONE!! [setting up terminal and OS specific settings]\n\n${RST}"


  # Finally set-up Homebrew for software packages
  brew -v || {
    printf "${CLI}> setting up Homebrew for package install:\n\n${RST}"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" || exit 1
  }
  # and that's it for OS X - let's get on with installing packages
}

echo "${CLI}> linking dotfiles/dirs:${RST}"
#XXX/TODO(azet): integrate bar per file for status bar etc.
for file in "${__incl_dotfiles[@]}"; do
  {
    ln -sF "${PWD}/${file}" "${HOME}/${file}" 
  }  && echo "${CLI}| - linked ${PWD}/${file} to ${HOME}/${file}.${RST}"  \
     || echo "${ERR}! - ${file} could not be linked to ${HOME}/${file}. ${RST}"
done

# Set-up specified software packages for running OS/Distro
install_pkgs


#XXX/TODO(azet): add python pips / ruby gems
#XXX/TODO(azet): link all the things

#EOF
