#!/usr/bin/env bash
#
# Bootstraps user environment and software toolchain
#
set -oe pipefail

## lib functions
source lib/os.inc
source lib/bar.inc

### NCPU workaround, portable (POSIX, MacOSX), plus jobs/threads
{
  cores=$(getconf _NPROCESSORS_ONLN)
  declare __dot_jobs="$((${cores}*2))"
}

## config
source bootstrap.conf


# ----------------------
# main bootstrap process
# ----------------------

# bootstrap submodules
echo "${CLI}> initializing, updating and pulling git submodules:${RST}"
{
  git submodule sync --recursive
  git submodule update --init --recursive --jobs ${__dot_jobs} --depth 2 -f
  git submodule foreach 'echo $sm_path `git rev-parse HEAD && git status`'
} && printf "\n\n${CLI}> git submodules updated!${RST}\n" \
  || ( printf "${ERR}! error updating git submodules.. !! BUT CONTINUING !! ${RST} \n\n" )


printf "${CLI}> will need super-user privileges (sudo) soon.. so I need your ${RST}"
{
  sudo printf "${CLI}\n> -- got sudo privs. --\n${RST}"
} || ( printf "${EXI}[-]\n! error obtaining sudo privs. !! EXITING !! ${RST}\n\n" && exit 1 )


# zsh - zshell
## zsh relevant default conf: grml
printf "${CLI}> adding /etc/zshrc from grml zsh:  "
{
  sudo curl --output /etc/zshrc https://raw.githubusercontent.com/grml/grml-etc-core/master/etc/zsh/zshrc -s
} && printf "[x]\n${RST}" \
  || ( printf "${EXI}[-]\n! error downloading and setting zshrc in /etc !! EXITING !! \n\n${RST}" && exit 1 )

## znap
printf "${CLI}> znap: zshell plugin mgr:  "
{
  [[ -r "~/.local/znap/znap.zsh" ]] || git clone --depth 1 -- \
    https://github.com/marlonrichert/zsh-snap.git ~/.local/znap &> /dev/null

  /usr/bin/env zsh -c "source ~/.local/znap/znap.zsh && \
     znap clone \
     git@github.com:zsh-users/zsh-completions.git \
     git@github.com:zsh-users/zsh-syntax-highlighting.git \
     git@github.com:mafredri/zsh-async.git \
     git@github.com:rupa/z.git \
     git@github.com:robbyrussell/oh-my-zsh.git \
     git@github.com:sorin-ionescu/prezto.git \
     git@github.com:sindresorhus/pure.git \
     git@github.com:ael-code/zsh-colored-man-pages.git \
     git@github.com:momo-lab/zsh-abbrev-alias.git \
     git@github.com:Aloxaf/fzf-tab.git \
     git@github.com:zsh-users/zsh-autosuggestions.git \
     git@github.com:softmoth/zsh-vim-mode.git"

} && printf "[x]\n> znap ~~ status \t.\t.\t.\n${RST}" && /usr/bin/env zsh -c "source ~/.local/znap/znap.zsh && znap status" \
  || ( printf "${EXI}[-]\n! error downloading and setting znap !! EXITING !! \n\n${RST}" && exit 1 )

## prezto
printf "${CLI}> zsh prezto option (managed via znap in .zshrc.local):  "
{
  [[ -r "~/.local/zprezto" ]] || git clone --recursive https://github.com/sorin-ionescu/prezto.git "~/.local/zprezto" &>/dev/null 
} && printf "[x]\n${RST}" \
  || ( printf "${EXI}[-]\n! error downloading and setting zsh prezto !! EXITING !! \n\n${RST}" && exit 1 )

## foreign setups
printf "${CLI}> setting up extra support tools for bat(1):${RST}"
[[ ! -d "${__dot_foreign_path}/bat-extras" ]] || {
  cd "${__dot_foreign_path}/bat-extras" ; ./build.sh &>/dev/null
} && printf "\t[x]\n" \
  || printf "${ERR}! ~ encountered problem setting up bat(1) support tools${RST}\n\n" 

# VIM vi improved
## vim janus config
printf "${CLI}> adding and bootstrapping vim janus and pathogen config: "
{
  curl -s -L https://bit.ly/janus-bootstrap | bash &>/dev/null
  mkdir -p ~/.vim/autoload ~/.vim/bundle && \
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  mkdir -p ~/.vim/pack/flake8/start/
  cd ~/.vim/pack/flake8/start/
  git clone https://github.com/nvie/vim-flake8.git -q
} && printf "[x]\n${RST}" \
  || ( printf "${ERR}! error bootstrapping vim janus.. !! BUT CONTINUING !! ${RST} \n\n" )

# OS/Distro relevant changes

## OS X Usability changes, Terminal settings etc.
## [ note: quite a lot of this has been copied from elsewhere, from people that maintain & ]
## [ regularly update preferences and checks relevant to change OS X system configs, plist ]
## [ entries and settings. In this case particularly from kdeldycke/dotfiles - thanks!     ]
[[ $(is_os?) == "macosx" ]] && {
  # get rid of macvim due to conflicts and we want a prestine version with plugins etc
  brew unlink macvim

  # First close system prefs so nothing can overwrite the following changes
  osascript -e 'tell application "System Preferences" to quit'

  # verbose boot (kernel bootup instead of loading Apple screen)
  printf "${CLI}> attempting to set verbose boot\n${RST}" && sudo nvram boot-args="-v"
  
  # make zsh universal default
  printf "${CLI}> make zsh universal default shell\n${RST}"
  sudo chsh -s /bin/zsh $USERNAME
  sudo chsh -s /bin/zsh root
  
  # set developer mode
  printf "${CLI}> setting dev mode\n\n${RST}"
  sudo spctl developer-mode enable-terminal


  printf "${CLI}> installing xcode cli tools\n\n${RST}"
  [[ -d "/Library/Developer/CommandLineTools" ]] || $(xcode-select --install)
  printf "${CLI}> setting terminal specific options:\n\n"
  # Only use UTF-8 in Terminal.app
  printf "| - utf8 only  "
  defaults write com.apple.terminal StringEncodings -array "4" && printf "[x]\n"
  
  # Enable “focus follows mouse” for Terminal.app and all X11 apps
  # i.e. hover over a window and start typing in it without clicking first
  printf "| - follow mouse focus with multiple open windows  "
  defaults write com.apple.terminal FocusFollowsMouse -bool true &&
  defaults write org.x.X11 wm_ffm -bool true 			 &&
  defaults write org.x.X11 wm_click_through -bool true		 && printf "[x]\n"

  # Enable Secure Keyboard Entry in Terminal.app
  # See: https://security.stackexchange.com/a/47786/8918
  printf "| - secure keyboard entry  "
  defaults write com.apple.terminal SecureKeyboardEntry -bool true && printf "[x]\n"

  printf "| - finally set misc terminal.app config settings..\n"
  # Disable the annoying line marks
  defaults write com.apple.Terminal ShowLineMarks -int 0

  printf "| - ..and copy com.apple.Terminal.plist to ~/Library/Preferences/\n"
  # Copy my personal terminal plist settings to my user preferences
  cp dist/osx/plists/com.apple.Terminal.plist ~/Library/Preferences/
  printf "| - !!DONE!! [setting up terminal and OS specific settings]\n\n${RST}"

## disabled due to docker-desktop Homebrew Cask
#  # set up docker for MacOS (apple silicon edition)
#  [[ -f /Applications/Docker.app/Contents/MacOS/Docker\ Desktop.app/Contents/MacOS/Docker\ Desktop ]] || {
#    printf "${CLI}> setting up docker for MacOS (Apple Silicon).. ${RST}"
#    [[ -f ${PWD}/Downloads/Docker.dmg ]] || curl -s https://desktop.docker.com/mac/main/arm64/Docker.dmg -o /Users/azet/Downloads/Docker.dmg
#    sudo hdiutil attach /Users/azet/Downloads/Docker.dmg &>/dev/null;
#    sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
#    sudo hdiutil detach /Volumes/Docker &>/dev/null
#  } && echo "${CLI}! - set up Docker.app in /Applications for MacOS ${RST}" \
#    || echo "${ERR}!!! failed docker setup !!!${RST}"


  # Finally set-up Homebrew for software packages
  brew -v &>/dev/null || {
    printf "${CLI}> setting up Homebrew for package install:\n\n${RST}"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" || exit 1
  }
  # and that's it for OS X - let's get on with installing packages
}



## setup tmux specifics
### TPM / tmux package manager
[[ -d "~/.tmux/plugins/tpm" ]] || { git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm }

echo "${CLI}> linking dotfiles/dirs:${RST}"
#XXX/TODO(azet): integrate bar per file for status bar etc.
for file in "${__incl_dotfiles[@]}"; do
  {
    ln -sF "${PWD}/${file}" "${HOME}/${file}" 
  }  && echo "${CLI}| - linked ${PWD}/${file} to ${HOME}/${file}.${RST}"  \
     || echo "${ERR}! - ${file} could not be linked to ${HOME}/${file}. ${RST}"
done

# Set-up specified software packages for running OS/Distro
install_pkgs


#XXX/TODO(azet): add python pips / ruby gems

#EOF
