#!/usr/bin/env bash
set -eu -o pipefail

# lib functions
source lib/os.inc

# config
source bootstrap.conf

## Main update routine
git pull --all --progress -q

echo "-------------------------------------------------------"
git show --oneline --pretty HEAD@{0}
echo "-------------------------------------------------------"

#git verify-commit HEAD@{0} &>/dev/null || exit 1
#printf "\n >> signature on commit verified.\n\n"

items=$(git diff --name-only HEAD@{1} HEAD@{0})
blacklist=(.gitignore .gitmodules)
[[ ${items} ]] && \
  for item in ${items}; do
    # make sure we only link dotfiles/dirs
    [[ ${item:0:1} == "." ]] && [[ ${item} =~ ${!blacklist[@]} ]] && \
    ln -shF "${PWD}/${item}" "${HOME}/${item}" && printf "  '%s' > linked to your home-directory\n" ${item}
  done ; echo

[[ $(is_os?) == "macosx" ]] && {
  brew update -q --auto-update 
  brew upgrade -gvi --ask --require-sha
  brew cleanup -sv
  brew doctor -vDd
}


/usr/bin/env zsh -c "source ~/.zsh-plugins/zsh-snap/znap.zsh && znap pull && znap clean && zprezto-update"

printf "\tFINISHED UPDATING\n\n"

#EOF
