#keyserver
keyserver-options ca-cert-file=/home/azet/.gnupg/sks-keyservers.cert.pem no-honor-keyserver-url include-revoked no-honor-keyserver-url include-revoked
auto-key-locate cert pka ldap hkps://hkps.pool.sks-keyservers.net

default-key A501FDC239AF0DB0DD4509662C83205B7CB34E69
personal-cipher-preferences AES256 AES
personal-digest-preferences SHA512 SHA384 SHA256
cert-digest-algo SHA512
require-cross-certification

keyid-format 0xlong
no-emit-version
use-agent
with-fingerprint
fixed-list-mode

verify-options show-uid-validity
list-options show-uid-validity

default-preference-list SHA512 SHA384 SHA256 AES256 AES ZLIB BZIP2 Uncompressed

auto-key-retrieve

#EOF
